### ISSUE TITLE
About APPID

### ISSUE THREAD

**Issue by coolkit-carl** [benchdog93/Home-Assistant-config#1]
Hello,

I'm the technical staff of CoolKit eWeLink, how did you get our APPID and APP Secret?

**Comment by benchdog93** [comment]
I did not know that I had them so I am not sure what you are asking me. I am new to HA and just learning how things work. Where would they be in my configuration? I will remove them once I know where to look. I did purchase 2 sonoff door/window contacts that would not connect with zigbee2mqtt so I added a second zigbee stick and installed ZHA integration and I was able to load the contacts.

**Comment by coolkit-carl** [comment]
> I did not know that I had them so I am not sure what you are asking me. I am new to HA and just learning how things work. Where would they be in my configuration? I will remove them once I know where to look. I did purchase 2 sonoff door/window contacts that would not connect with zigbee2mqtt so I added a second zigbee stick and installed ZHA integration and I was able to load the contacts.

OK, it's OK. I've got the final author,

**Comment by benchdog93** [comment]
Should I be removing the integration? I don't want to be doing anything wrong.

**Comment by coolkit-carl** [comment]
> Should I be removing the integration? I don't want to be doing anything wrong.

No need to remove it for the time being. It has nothing to do with you. If I need your help, I will contact you again.

**Comment by benchdog93** [comment]
Thank you
